// <auto-generated />
using System;
using HospitalSys.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HospitalSys.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260618045509_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HospitalSys.Models.BillingAndPayment.Bill", b =>
                {
                    b.Property<int>("BillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BillID"));

                    b.Property<DateTime>("BillDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CashierID")
                        .HasColumnType("integer");

                    b.Property<int>("PatientID")
                        .HasColumnType("integer");

                    b.Property<int?>("PatientVistVistID")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("double precision");

                    b.Property<int>("VisitID")
                        .HasColumnType("integer");

                    b.HasKey("BillID");

                    b.HasIndex("CashierID");

                    b.HasIndex("PatientID");

                    b.HasIndex("PatientVistVistID");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("HospitalSys.Models.BillingAndPayment.BillItem", b =>
                {
                    b.Property<int>("BillItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BillItemID"));

                    b.Property<int>("BillID")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceName")
                        .HasColumnType("text");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("double precision");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("double precision");

                    b.HasKey("BillItemID");

                    b.HasIndex("BillID");

                    b.ToTable("BillItems");
                });

            modelBuilder.Entity("HospitalSys.Models.BillingAndPayment.PaymentHospital", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentID"));

                    b.Property<double>("AmountPaid")
                        .HasColumnType("double precision");

                    b.Property<int>("BillID")
                        .HasColumnType("integer");

                    b.Property<int>("CashierID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PaymentID");

                    b.HasIndex("BillID");

                    b.HasIndex("CashierID");

                    b.ToTable("PaymentHospitals");
                });

            modelBuilder.Entity("HospitalSys.Models.BillingAndPayment.PharmacyPayment", b =>
                {
                    b.Property<int>("PharmacyPaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PharmacyPaymentID"));

                    b.Property<double>("AmountPaid")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PharmacyCashierID")
                        .HasColumnType("integer");

                    b.Property<int>("PrescriptionID")
                        .HasColumnType("integer");

                    b.HasKey("PharmacyPaymentID");

                    b.HasIndex("PharmacyCashierID");

                    b.HasIndex("PrescriptionID");

                    b.ToTable("PharmacyPayments");
                });

            modelBuilder.Entity("HospitalSys.Models.Cashier", b =>
                {
                    b.Property<int>("CashierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CashierID"));

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<int?>("UsersUserID")
                        .HasColumnType("integer");

                    b.HasKey("CashierID");

                    b.HasIndex("UsersUserID");

                    b.ToTable("Cashiers");
                });

            modelBuilder.Entity("HospitalSys.Models.Consultation_M.Consultation", b =>
                {
                    b.Property<int>("ConsultationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConsultationID"));

                    b.Property<string>("ChiefComplaint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ConsultationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DoctorID")
                        .HasColumnType("integer");

                    b.Property<int?>("PatientVistVistID")
                        .HasColumnType("integer");

                    b.Property<string>("TreatmentPlan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VisitID")
                        .HasColumnType("integer");

                    b.HasKey("ConsultationID");

                    b.HasIndex("DoctorID");

                    b.HasIndex("PatientVistVistID");

                    b.ToTable("Consultations");
                });

            modelBuilder.Entity("HospitalSys.Models.Consultation_M.MedicalRecord", b =>
                {
                    b.Property<int>("MedicalRecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MedicalRecordID"));

                    b.Property<int>("ConsultationID")
                        .HasColumnType("integer");

                    b.Property<int>("DoctorID")
                        .HasColumnType("integer");

                    b.Property<int>("PatientID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RecordTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MedicalRecordID");

                    b.HasIndex("ConsultationID");

                    b.HasIndex("DoctorID");

                    b.HasIndex("PatientID");

                    b.ToTable("MedicalRecords");
                });

            modelBuilder.Entity("HospitalSys.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DoctorID"));

                    b.Property<int>("ClinicalDepartmentID")
                        .HasMaxLength(200)
                        .HasColumnType("integer");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<int?>("UsersUserID")
                        .HasColumnType("integer");

                    b.HasKey("DoctorID");

                    b.HasIndex("ClinicalDepartmentID");

                    b.HasIndex("UsersUserID");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("HospitalSys.Models.HospitalStruct.Bed", b =>
                {
                    b.Property<int>("BedID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BedID"));

                    b.Property<string>("BedNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RoomID")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BedID");

                    b.HasIndex("RoomID");

                    b.ToTable("Beds");
                });

            modelBuilder.Entity("HospitalSys.Models.HospitalStruct.ClinicalDepartment", b =>
                {
                    b.Property<int>("ClinicalDepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClinicalDepartmentID"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("ClinicalDepartmentID");

                    b.ToTable("ClinicalDepartment");
                });

            modelBuilder.Entity("HospitalSys.Models.HospitalStruct.Room", b =>
                {
                    b.Property<int>("RoomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoomID"));

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("WardID")
                        .HasColumnType("integer");

                    b.HasKey("RoomID");

                    b.HasIndex("WardID");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("HospitalSys.Models.HospitalStruct.TriageDepartment", b =>
                {
                    b.Property<int>("TriageDepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TriageDepartmentID"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("TriageDepartmentID");

                    b.ToTable("TriageDepartment");
                });

            modelBuilder.Entity("HospitalSys.Models.HospitalStruct.Ward", b =>
                {
                    b.Property<int>("WardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WardID"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("WardName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("WardID");

                    b.ToTable("Wards");
                });

            modelBuilder.Entity("HospitalSys.Models.Inpatient.Admission", b =>
                {
                    b.Property<int>("AdmissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AdmissionID"));

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BedID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DischargeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DoctorID")
                        .HasColumnType("integer");

                    b.Property<int>("PatientID")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AdmissionID");

                    b.HasIndex("BedID");

                    b.HasIndex("DoctorID");

                    b.HasIndex("PatientID");

                    b.ToTable("Admissions");
                });

            modelBuilder.Entity("HospitalSys.Models.LaboratoryTechnician", b =>
                {
                    b.Property<int>("TechnicianID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TechnicianID"));

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<int?>("UsersUserID")
                        .HasColumnType("integer");

                    b.HasKey("TechnicianID");

                    b.HasIndex("UsersUserID");

                    b.ToTable("LaboratoryTechnicians");
                });

            modelBuilder.Entity("HospitalSys.Models.Nurse", b =>
                {
                    b.Property<int>("NurseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NurseID"));

                    b.Property<int>("ClinicalDepartmentID")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<int?>("UsersUserID")
                        .HasColumnType("integer");

                    b.HasKey("NurseID");

                    b.HasIndex("ClinicalDepartmentID");

                    b.HasIndex("UsersUserID");

                    b.ToTable("Nurses");
                });

            modelBuilder.Entity("HospitalSys.Models.PatientManagment.Appointment", b =>
                {
                    b.Property<int>("AppointmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AppointmentID"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DoctorID")
                        .HasColumnType("integer");

                    b.Property<int>("PatientID")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("AppointmentID");

                    b.HasIndex("DoctorID");

                    b.HasIndex("PatientID");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("HospitalSys.Models.PatientManagment.Patient", b =>
                {
                    b.Property<int>("PatientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PatientID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmergencyContact")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("PatientID");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("HospitalSys.Models.PatientManagment.PatientVist", b =>
                {
                    b.Property<int>("VistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VistID"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PatientID")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VistType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VistID");

                    b.HasIndex("PatientID");

                    b.ToTable("PatientVists");
                });

            modelBuilder.Entity("HospitalSys.Models.PatientManagment.Triage", b =>
                {
                    b.Property<int>("TriageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TriageId"));

                    b.Property<double>("BloodPressure")
                        .HasColumnType("double precision");

                    b.Property<int>("ClinicalDepartmentID")
                        .HasColumnType("integer");

                    b.Property<double>("HeartRate")
                        .HasColumnType("double precision");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NurseID")
                        .HasColumnType("integer");

                    b.Property<int?>("PatientVistVistID")
                        .HasColumnType("integer");

                    b.Property<double>("RespiratotyRate")
                        .HasColumnType("double precision");

                    b.Property<double>("Temprature")
                        .HasColumnType("double precision");

                    b.Property<int>("TriageDepartmentID")
                        .HasColumnType("integer");

                    b.Property<int>("VistID")
                        .HasColumnType("integer");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("TriageId");

                    b.HasIndex("ClinicalDepartmentID");

                    b.HasIndex("NurseID");

                    b.HasIndex("PatientVistVistID");

                    b.HasIndex("TriageDepartmentID");

                    b.ToTable("Triages");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacist", b =>
                {
                    b.Property<int>("PharmacistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PharmacistID"));

                    b.Property<int>("BranchPharmacyID")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<int?>("UsersUserID")
                        .HasColumnType("integer");

                    b.HasKey("PharmacistID");

                    b.HasIndex("BranchPharmacyID");

                    b.HasIndex("UsersUserID");

                    b.ToTable("Pharmacists");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.AidStore.AidStoreInventory", b =>
                {
                    b.Property<int>("AidInventoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AidInventoryID"));

                    b.Property<int>("AidPharmacyID")
                        .HasColumnType("integer");

                    b.Property<int?>("AidStorePharmacyAidPharmacyID")
                        .HasColumnType("integer");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MedicineID")
                        .HasColumnType("integer");

                    b.Property<float>("QuantityAvailable")
                        .HasColumnType("real");

                    b.HasKey("AidInventoryID");

                    b.HasIndex("AidStorePharmacyAidPharmacyID");

                    b.HasIndex("MedicineID");

                    b.ToTable("AidStoreInventories");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.AidStore.AidStorePharmacy", b =>
                {
                    b.Property<int>("AidPharmacyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AidPharmacyID"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ManagerPharmacistID")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UsersUserID")
                        .HasColumnType("integer");

                    b.HasKey("AidPharmacyID");

                    b.HasIndex("UsersUserID");

                    b.ToTable("AidStorePharmacies");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.AidStore.AidStoreRequest", b =>
                {
                    b.Property<int>("AidRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AidRequestID"));

                    b.Property<int>("BranchPharmacyID")
                        .HasColumnType("integer");

                    b.Property<int?>("PharmacistID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RequestedByPharmacistID")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AidRequestID");

                    b.HasIndex("BranchPharmacyID");

                    b.HasIndex("PharmacistID");

                    b.ToTable("AidStoreRequests");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.AidStore.AidStoreRequestDetail", b =>
                {
                    b.Property<int>("AidRequestDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AidRequestDetailID"));

                    b.Property<int>("AidRequestID")
                        .HasColumnType("integer");

                    b.Property<int?>("AidStoreRequestAidRequestID")
                        .HasColumnType("integer");

                    b.Property<int>("ApprovedQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("MedicineID")
                        .HasColumnType("integer");

                    b.Property<int>("RequestedQuantity")
                        .HasColumnType("integer");

                    b.HasKey("AidRequestDetailID");

                    b.HasIndex("AidStoreRequestAidRequestID");

                    b.HasIndex("MedicineID");

                    b.ToTable("AidStoreRequestDetails");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.AidStore.AidStoreTransfer", b =>
                {
                    b.Property<int>("AidTransferID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AidTransferID"));

                    b.Property<int>("AidPharmacyID")
                        .HasColumnType("integer");

                    b.Property<int>("AidRequestID")
                        .HasColumnType("integer");

                    b.Property<int?>("AidStorePharmacyAidPharmacyID")
                        .HasColumnType("integer");

                    b.Property<int?>("AidStoreRequestAidRequestID")
                        .HasColumnType("integer");

                    b.Property<int>("BranchPharmacyID")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TransferDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AidTransferID");

                    b.HasIndex("AidStorePharmacyAidPharmacyID");

                    b.HasIndex("AidStoreRequestAidRequestID");

                    b.HasIndex("BranchPharmacyID");

                    b.ToTable("AidStoreTransfers");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.AidStore.AidStoreTransferDetail", b =>
                {
                    b.Property<int>("AidTransferDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AidTransferDetailID"));

                    b.Property<int?>("AidStoreTransferAidTransferID")
                        .HasColumnType("integer");

                    b.Property<int>("AidTransferID")
                        .HasColumnType("integer");

                    b.Property<int>("MedicineID")
                        .HasColumnType("integer");

                    b.Property<int>("QuantityTransferred")
                        .HasColumnType("integer");

                    b.HasKey("AidTransferDetailID");

                    b.HasIndex("AidStoreTransferAidTransferID");

                    b.HasIndex("MedicineID");

                    b.ToTable("AidStoreTransferDetails");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.Branch.BranchInventory", b =>
                {
                    b.Property<int>("BranchInventoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BranchInventoryID"));

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BranchPharmacyID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MedicineID")
                        .HasColumnType("integer");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("integer");

                    b.HasKey("BranchInventoryID");

                    b.HasIndex("BranchPharmacyID");

                    b.HasIndex("MedicineID");

                    b.ToTable("BranchInventories");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.Branch.BranchPharmacy", b =>
                {
                    b.Property<int>("BranchPharmacyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BranchPharmacyID"));

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BranchPharmacyID");

                    b.ToTable("BranchPharmacies");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.CentralStore.CentralStoreInventory", b =>
                {
                    b.Property<int>("CentralInventoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CentralInventoryID"));

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CentralPharmacyID")
                        .HasColumnType("integer");

                    b.Property<int?>("CentralStorePharmacyCentralPharmacyID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MedicineID")
                        .HasColumnType("integer");

                    b.Property<float>("QuantityAvailable")
                        .HasColumnType("real");

                    b.HasKey("CentralInventoryID");

                    b.HasIndex("CentralStorePharmacyCentralPharmacyID");

                    b.HasIndex("MedicineID");

                    b.ToTable("CentralStoreInventories");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.CentralStore.CentralStorePharmacy", b =>
                {
                    b.Property<int>("CentralPharmacyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CentralPharmacyID"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ManagerPharmacistID")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UsersUserID")
                        .HasColumnType("integer");

                    b.HasKey("CentralPharmacyID");

                    b.HasIndex("UsersUserID");

                    b.ToTable("CentralStorePharmacies");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.CentralStore.CentralStoreRequest", b =>
                {
                    b.Property<int>("CentralRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CentralRequestID"));

                    b.Property<int>("BranchPharmacyID")
                        .HasColumnType("integer");

                    b.Property<int?>("PharmacistID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RequestedByPharmacistID")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CentralRequestID");

                    b.HasIndex("BranchPharmacyID");

                    b.HasIndex("PharmacistID");

                    b.ToTable("CentralStoreRequests");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.CentralStore.CentralStoreRequestDetail", b =>
                {
                    b.Property<int>("CentralRequestDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CentralRequestDetailID"));

                    b.Property<int>("ApprovedQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("CentralRequestID")
                        .HasColumnType("integer");

                    b.Property<int?>("CentralStoreRequestCentralRequestID")
                        .HasColumnType("integer");

                    b.Property<int>("MedicineID")
                        .HasColumnType("integer");

                    b.Property<int>("RequestedQuantity")
                        .HasColumnType("integer");

                    b.HasKey("CentralRequestDetailID");

                    b.HasIndex("CentralStoreRequestCentralRequestID");

                    b.HasIndex("MedicineID");

                    b.ToTable("CentralStoreRequestDetails");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.CentralStore.CentralStoreTransfer", b =>
                {
                    b.Property<int>("CentralTransferID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CentralTransferID"));

                    b.Property<int>("BranchPharmacyID")
                        .HasColumnType("integer");

                    b.Property<int>("CentralPharmacyID")
                        .HasColumnType("integer");

                    b.Property<int>("CentralRequestID")
                        .HasColumnType("integer");

                    b.Property<int?>("CentralStorePharmacyCentralPharmacyID")
                        .HasColumnType("integer");

                    b.Property<int?>("CentralStoreRequestCentralRequestID")
                        .HasColumnType("integer");

                    b.Property<int?>("MedicineID")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TransferDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CentralTransferID");

                    b.HasIndex("BranchPharmacyID");

                    b.HasIndex("CentralStorePharmacyCentralPharmacyID");

                    b.HasIndex("CentralStoreRequestCentralRequestID");

                    b.HasIndex("MedicineID");

                    b.ToTable("CentralStoreTransfers");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.CentralStore.CentralStoreTransferDetail", b =>
                {
                    b.Property<int>("CentralTransferDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CentralTransferDetailID"));

                    b.Property<int?>("CentralStoreTransferCentralTransferID")
                        .HasColumnType("integer");

                    b.Property<int>("CentralTransferID")
                        .HasColumnType("integer");

                    b.Property<int>("MedicineID")
                        .HasColumnType("integer");

                    b.Property<int>("QuantityTransferred")
                        .HasColumnType("integer");

                    b.HasKey("CentralTransferDetailID");

                    b.HasIndex("CentralStoreTransferCentralTransferID");

                    b.HasIndex("MedicineID");

                    b.ToTable("CentralStoreTransferDetails");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.Common.DispenseMedicine", b =>
                {
                    b.Property<int>("DispenseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DispenseID"));

                    b.Property<int>("BranchPharmacyID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DispenceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PharmacistID")
                        .HasColumnType("integer");

                    b.Property<int>("PrescriptionID")
                        .HasColumnType("integer");

                    b.HasKey("DispenseID");

                    b.HasIndex("BranchPharmacyID");

                    b.HasIndex("PharmacistID");

                    b.HasIndex("PrescriptionID");

                    b.ToTable("DispenseMedicines");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.Common.DispenseMedicineDetail", b =>
                {
                    b.Property<int>("DispenseDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DispenseDetailID"));

                    b.Property<int>("DispenseID")
                        .HasColumnType("integer");

                    b.Property<int?>("DispenseMedicineDispenseID")
                        .HasColumnType("integer");

                    b.Property<int>("MedicineID")
                        .HasColumnType("integer");

                    b.Property<float>("QuantityDispenced")
                        .HasColumnType("real");

                    b.HasKey("DispenseDetailID");

                    b.HasIndex("DispenseMedicineDispenseID");

                    b.HasIndex("MedicineID");

                    b.ToTable("DispenseMedicineDetails");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.Common.Medicine", b =>
                {
                    b.Property<int>("MedicineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MedicineID"));

                    b.Property<string>("GenericName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("double precision");

                    b.HasKey("MedicineID");

                    b.ToTable("Medicines");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.Common.Prescription", b =>
                {
                    b.Property<int>("PrescriptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PrescriptionID"));

                    b.Property<int>("BranchPharmacyID")
                        .HasColumnType("integer");

                    b.Property<int>("ConsultationID")
                        .HasColumnType("integer");

                    b.Property<int>("DoctorID")
                        .HasColumnType("integer");

                    b.Property<int>("PatientID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PrescriptionDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PrescriptionID");

                    b.HasIndex("BranchPharmacyID");

                    b.HasIndex("ConsultationID");

                    b.HasIndex("DoctorID");

                    b.HasIndex("PatientID");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.Common.PrescriptionDetail", b =>
                {
                    b.Property<int>("PrescriptionDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PrescriptionDetailID"));

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Duration")
                        .HasColumnType("real");

                    b.Property<float>("Frequency")
                        .HasColumnType("real");

                    b.Property<int>("MedicineID")
                        .HasColumnType("integer");

                    b.Property<int>("PrescriptionID")
                        .HasColumnType("integer");

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.HasKey("PrescriptionDetailID");

                    b.HasIndex("MedicineID");

                    b.HasIndex("PrescriptionID");

                    b.ToTable("PrescriptionDetails");
                });

            modelBuilder.Entity("HospitalSys.Models.PharmacyCashier", b =>
                {
                    b.Property<int>("PharmacyCashierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PharmacyCashierID"));

                    b.Property<int>("BranchPharmacyID")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<int?>("UsersUserID")
                        .HasColumnType("integer");

                    b.HasKey("PharmacyCashierID");

                    b.HasIndex("BranchPharmacyID");

                    b.HasIndex("UsersUserID");

                    b.ToTable("PharmacyCashiers");
                });

            modelBuilder.Entity("HospitalSys.Models.Receptionist", b =>
                {
                    b.Property<int>("ReceptionistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReceptionistID"));

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<int?>("UsersUserID")
                        .HasColumnType("integer");

                    b.HasKey("ReceptionistID");

                    b.HasIndex("UsersUserID");

                    b.ToTable("Receptionists");
                });

            modelBuilder.Entity("HospitalSys.Models.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleID"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("HospitalSys.Models.SuperAdmins", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("AdminRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ID");

                    b.ToTable("SuperAdmin");
                });

            modelBuilder.Entity("HospitalSys.Models.Users", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("RoleID")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("UserID");

                    b.HasIndex("RoleID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HospitalSys.Models.BillingAndPayment.Bill", b =>
                {
                    b.HasOne("HospitalSys.Models.Cashier", "Cashier")
                        .WithMany("Bill")
                        .HasForeignKey("CashierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalSys.Models.PatientManagment.Patient", "Patient")
                        .WithMany("Bill")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalSys.Models.PatientManagment.PatientVist", "PatientVist")
                        .WithMany("Bill")
                        .HasForeignKey("PatientVistVistID");

                    b.Navigation("Cashier");

                    b.Navigation("Patient");

                    b.Navigation("PatientVist");
                });

            modelBuilder.Entity("HospitalSys.Models.BillingAndPayment.BillItem", b =>
                {
                    b.HasOne("HospitalSys.Models.BillingAndPayment.Bill", "Bill")
                        .WithMany("BillItem")
                        .HasForeignKey("BillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("HospitalSys.Models.BillingAndPayment.PaymentHospital", b =>
                {
                    b.HasOne("HospitalSys.Models.BillingAndPayment.Bill", "Bill")
                        .WithMany("PaymentHospital")
                        .HasForeignKey("BillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalSys.Models.Cashier", "Cashier")
                        .WithMany("PaymentHospital")
                        .HasForeignKey("CashierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("Cashier");
                });

            modelBuilder.Entity("HospitalSys.Models.BillingAndPayment.PharmacyPayment", b =>
                {
                    b.HasOne("HospitalSys.Models.PharmacyCashier", "PharmacyCashier")
                        .WithMany("PharmacyPayment")
                        .HasForeignKey("PharmacyCashierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalSys.Models.Pharmacy.Common.Prescription", "Prescription")
                        .WithMany("PharmacyPayment")
                        .HasForeignKey("PrescriptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PharmacyCashier");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("HospitalSys.Models.Cashier", b =>
                {
                    b.HasOne("HospitalSys.Models.Users", "Users")
                        .WithMany("Cashier")
                        .HasForeignKey("UsersUserID");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("HospitalSys.Models.Consultation_M.Consultation", b =>
                {
                    b.HasOne("HospitalSys.Models.Doctor", "Doctor")
                        .WithMany("Consultation")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalSys.Models.PatientManagment.PatientVist", "PatientVist")
                        .WithMany("Consultation")
                        .HasForeignKey("PatientVistVistID");

                    b.Navigation("Doctor");

                    b.Navigation("PatientVist");
                });

            modelBuilder.Entity("HospitalSys.Models.Consultation_M.MedicalRecord", b =>
                {
                    b.HasOne("HospitalSys.Models.Consultation_M.Consultation", "Consultation")
                        .WithMany("MedicalRecord")
                        .HasForeignKey("ConsultationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalSys.Models.Doctor", "Doctor")
                        .WithMany("MedicalRecord")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalSys.Models.PatientManagment.Patient", "Patient")
                        .WithMany("MedicalRecord")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultation");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalSys.Models.Doctor", b =>
                {
                    b.HasOne("HospitalSys.Models.HospitalStruct.ClinicalDepartment", "ClinicalDepartment")
                        .WithMany("Doctor")
                        .HasForeignKey("ClinicalDepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalSys.Models.Users", "Users")
                        .WithMany("Doctor")
                        .HasForeignKey("UsersUserID");

                    b.Navigation("ClinicalDepartment");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("HospitalSys.Models.HospitalStruct.Bed", b =>
                {
                    b.HasOne("HospitalSys.Models.HospitalStruct.Room", "Room")
                        .WithMany("Bed")
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HospitalSys.Models.HospitalStruct.Room", b =>
                {
                    b.HasOne("HospitalSys.Models.HospitalStruct.Ward", "Ward")
                        .WithMany("Room")
                        .HasForeignKey("WardID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("HospitalSys.Models.Inpatient.Admission", b =>
                {
                    b.HasOne("HospitalSys.Models.HospitalStruct.Bed", "Bed")
                        .WithMany("Admission")
                        .HasForeignKey("BedID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalSys.Models.Doctor", "Doctor")
                        .WithMany("Admission")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalSys.Models.PatientManagment.Patient", "Patient")
                        .WithMany("Admission")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bed");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalSys.Models.LaboratoryTechnician", b =>
                {
                    b.HasOne("HospitalSys.Models.Users", "Users")
                        .WithMany("LaboratoryTechnician")
                        .HasForeignKey("UsersUserID");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("HospitalSys.Models.Nurse", b =>
                {
                    b.HasOne("HospitalSys.Models.HospitalStruct.ClinicalDepartment", "ClinicalDepartment")
                        .WithMany("Nurse")
                        .HasForeignKey("ClinicalDepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalSys.Models.Users", "Users")
                        .WithMany("Nurse")
                        .HasForeignKey("UsersUserID");

                    b.Navigation("ClinicalDepartment");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("HospitalSys.Models.PatientManagment.Appointment", b =>
                {
                    b.HasOne("HospitalSys.Models.Doctor", "Doctor")
                        .WithMany("Appointment")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalSys.Models.PatientManagment.Patient", "Patient")
                        .WithMany("Appointment")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalSys.Models.PatientManagment.PatientVist", b =>
                {
                    b.HasOne("HospitalSys.Models.PatientManagment.Patient", "Patient")
                        .WithMany("PatientVist")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalSys.Models.PatientManagment.Triage", b =>
                {
                    b.HasOne("HospitalSys.Models.HospitalStruct.ClinicalDepartment", "ClinicalDepartment")
                        .WithMany("Triage")
                        .HasForeignKey("ClinicalDepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalSys.Models.Nurse", "Nurse")
                        .WithMany("Triage")
                        .HasForeignKey("NurseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalSys.Models.PatientManagment.PatientVist", "PatientVist")
                        .WithMany("Triage")
                        .HasForeignKey("PatientVistVistID");

                    b.HasOne("HospitalSys.Models.HospitalStruct.TriageDepartment", "TriageDepartment")
                        .WithMany("Triage")
                        .HasForeignKey("TriageDepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClinicalDepartment");

                    b.Navigation("Nurse");

                    b.Navigation("PatientVist");

                    b.Navigation("TriageDepartment");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacist", b =>
                {
                    b.HasOne("HospitalSys.Models.Pharmacy.Branch.BranchPharmacy", "BranchPharmacy")
                        .WithMany("Pharmacist")
                        .HasForeignKey("BranchPharmacyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalSys.Models.Users", "Users")
                        .WithMany("Pharmacist")
                        .HasForeignKey("UsersUserID");

                    b.Navigation("BranchPharmacy");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.AidStore.AidStoreInventory", b =>
                {
                    b.HasOne("HospitalSys.Models.Pharmacy.AidStore.AidStorePharmacy", "AidStorePharmacy")
                        .WithMany("AidStoreInventory")
                        .HasForeignKey("AidStorePharmacyAidPharmacyID");

                    b.HasOne("HospitalSys.Models.Pharmacy.Common.Medicine", "Medicine")
                        .WithMany("AidStoreInventory")
                        .HasForeignKey("MedicineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AidStorePharmacy");

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.AidStore.AidStorePharmacy", b =>
                {
                    b.HasOne("HospitalSys.Models.Users", "Users")
                        .WithMany("AidStorePharmacy")
                        .HasForeignKey("UsersUserID");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.AidStore.AidStoreRequest", b =>
                {
                    b.HasOne("HospitalSys.Models.Pharmacy.Branch.BranchPharmacy", "BranchPharmacy")
                        .WithMany("AidStoreRequest")
                        .HasForeignKey("BranchPharmacyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalSys.Models.Pharmacist", "Pharmacist")
                        .WithMany("AidStoreRequest")
                        .HasForeignKey("PharmacistID");

                    b.Navigation("BranchPharmacy");

                    b.Navigation("Pharmacist");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.AidStore.AidStoreRequestDetail", b =>
                {
                    b.HasOne("HospitalSys.Models.Pharmacy.AidStore.AidStoreRequest", "AidStoreRequest")
                        .WithMany("AidStoreRequestDetail")
                        .HasForeignKey("AidStoreRequestAidRequestID");

                    b.HasOne("HospitalSys.Models.Pharmacy.Common.Medicine", "Medicine")
                        .WithMany("AidStoreRequestDetail")
                        .HasForeignKey("MedicineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AidStoreRequest");

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.AidStore.AidStoreTransfer", b =>
                {
                    b.HasOne("HospitalSys.Models.Pharmacy.AidStore.AidStorePharmacy", "AidStorePharmacy")
                        .WithMany("AidStoreTransfer")
                        .HasForeignKey("AidStorePharmacyAidPharmacyID");

                    b.HasOne("HospitalSys.Models.Pharmacy.AidStore.AidStoreRequest", "AidStoreRequest")
                        .WithMany("AidStoreTransfer")
                        .HasForeignKey("AidStoreRequestAidRequestID");

                    b.HasOne("HospitalSys.Models.Pharmacy.Branch.BranchPharmacy", "BranchPharmacy")
                        .WithMany("AidStoreTransfer")
                        .HasForeignKey("BranchPharmacyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AidStorePharmacy");

                    b.Navigation("AidStoreRequest");

                    b.Navigation("BranchPharmacy");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.AidStore.AidStoreTransferDetail", b =>
                {
                    b.HasOne("HospitalSys.Models.Pharmacy.AidStore.AidStoreTransfer", "AidStoreTransfer")
                        .WithMany("CentralStoreTransferDetail")
                        .HasForeignKey("AidStoreTransferAidTransferID");

                    b.HasOne("HospitalSys.Models.Pharmacy.Common.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AidStoreTransfer");

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.Branch.BranchInventory", b =>
                {
                    b.HasOne("HospitalSys.Models.Pharmacy.Branch.BranchPharmacy", "BranchPharmacy")
                        .WithMany("BranchInventory")
                        .HasForeignKey("BranchPharmacyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalSys.Models.Pharmacy.Common.Medicine", "Medicine")
                        .WithMany("BranchInventory")
                        .HasForeignKey("MedicineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BranchPharmacy");

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.CentralStore.CentralStoreInventory", b =>
                {
                    b.HasOne("HospitalSys.Models.Pharmacy.CentralStore.CentralStorePharmacy", "CentralStorePharmacy")
                        .WithMany("CentralStoreInventory")
                        .HasForeignKey("CentralStorePharmacyCentralPharmacyID");

                    b.HasOne("HospitalSys.Models.Pharmacy.Common.Medicine", "Medicine")
                        .WithMany("CentralStoreInventory")
                        .HasForeignKey("MedicineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CentralStorePharmacy");

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.CentralStore.CentralStorePharmacy", b =>
                {
                    b.HasOne("HospitalSys.Models.Users", "Users")
                        .WithMany("CentralStorePharmacy")
                        .HasForeignKey("UsersUserID");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.CentralStore.CentralStoreRequest", b =>
                {
                    b.HasOne("HospitalSys.Models.Pharmacy.Branch.BranchPharmacy", "BranchPharmacy")
                        .WithMany("CentralStoreRequest")
                        .HasForeignKey("BranchPharmacyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalSys.Models.Pharmacist", "Pharmacist")
                        .WithMany("CentralStoreRequest")
                        .HasForeignKey("PharmacistID");

                    b.Navigation("BranchPharmacy");

                    b.Navigation("Pharmacist");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.CentralStore.CentralStoreRequestDetail", b =>
                {
                    b.HasOne("HospitalSys.Models.Pharmacy.CentralStore.CentralStoreRequest", "CentralStoreRequest")
                        .WithMany("CentralStoreRequestDetail")
                        .HasForeignKey("CentralStoreRequestCentralRequestID");

                    b.HasOne("HospitalSys.Models.Pharmacy.Common.Medicine", "Medicine")
                        .WithMany("CentralStoreRequestDetail")
                        .HasForeignKey("MedicineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CentralStoreRequest");

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.CentralStore.CentralStoreTransfer", b =>
                {
                    b.HasOne("HospitalSys.Models.Pharmacy.Branch.BranchPharmacy", "BranchPharmacy")
                        .WithMany("CentralStoreTransfer")
                        .HasForeignKey("BranchPharmacyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalSys.Models.Pharmacy.CentralStore.CentralStorePharmacy", "CentralStorePharmacy")
                        .WithMany("CentralStoreTransfer")
                        .HasForeignKey("CentralStorePharmacyCentralPharmacyID");

                    b.HasOne("HospitalSys.Models.Pharmacy.CentralStore.CentralStoreRequest", "CentralStoreRequest")
                        .WithMany("CentralStoreTransfer")
                        .HasForeignKey("CentralStoreRequestCentralRequestID");

                    b.HasOne("HospitalSys.Models.Pharmacy.Common.Medicine", null)
                        .WithMany("CentralStoreTransfer")
                        .HasForeignKey("MedicineID");

                    b.Navigation("BranchPharmacy");

                    b.Navigation("CentralStorePharmacy");

                    b.Navigation("CentralStoreRequest");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.CentralStore.CentralStoreTransferDetail", b =>
                {
                    b.HasOne("HospitalSys.Models.Pharmacy.CentralStore.CentralStoreTransfer", "CentralStoreTransfer")
                        .WithMany("CentralStoreTransferDetail")
                        .HasForeignKey("CentralStoreTransferCentralTransferID");

                    b.HasOne("HospitalSys.Models.Pharmacy.Common.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CentralStoreTransfer");

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.Common.DispenseMedicine", b =>
                {
                    b.HasOne("HospitalSys.Models.Pharmacy.Branch.BranchPharmacy", "BranchPharmacy")
                        .WithMany("DispenseMedicine")
                        .HasForeignKey("BranchPharmacyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalSys.Models.Pharmacist", "Pharmacist")
                        .WithMany("DispenseMedicine")
                        .HasForeignKey("PharmacistID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalSys.Models.Pharmacy.Common.Prescription", "Prescription")
                        .WithMany("DispenseMedicine")
                        .HasForeignKey("PrescriptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BranchPharmacy");

                    b.Navigation("Pharmacist");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.Common.DispenseMedicineDetail", b =>
                {
                    b.HasOne("HospitalSys.Models.Pharmacy.Common.DispenseMedicine", "DispenseMedicine")
                        .WithMany("DispenseMedicineDetails")
                        .HasForeignKey("DispenseMedicineDispenseID");

                    b.HasOne("HospitalSys.Models.Pharmacy.Common.Medicine", "Medicine")
                        .WithMany("DispenseMedicineDetail")
                        .HasForeignKey("MedicineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DispenseMedicine");

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.Common.Prescription", b =>
                {
                    b.HasOne("HospitalSys.Models.Pharmacy.Branch.BranchPharmacy", "BranchPharmacy")
                        .WithMany("Prescription")
                        .HasForeignKey("BranchPharmacyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalSys.Models.Consultation_M.Consultation", "Consultation")
                        .WithMany("Prescription")
                        .HasForeignKey("ConsultationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalSys.Models.Doctor", "Doctor")
                        .WithMany("Prescription")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalSys.Models.PatientManagment.Patient", "Patient")
                        .WithMany("Prescription")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BranchPharmacy");

                    b.Navigation("Consultation");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.Common.PrescriptionDetail", b =>
                {
                    b.HasOne("HospitalSys.Models.Pharmacy.Common.Medicine", "Medicine")
                        .WithMany("PrescriptionDetail")
                        .HasForeignKey("MedicineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalSys.Models.Pharmacy.Common.Prescription", "Prescription")
                        .WithMany("PrescriptionDetail")
                        .HasForeignKey("PrescriptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("HospitalSys.Models.PharmacyCashier", b =>
                {
                    b.HasOne("HospitalSys.Models.Pharmacy.Branch.BranchPharmacy", "BranchPharmacy")
                        .WithMany("PharmacyCashier")
                        .HasForeignKey("BranchPharmacyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalSys.Models.Users", "Users")
                        .WithMany("PharmacyCashier")
                        .HasForeignKey("UsersUserID");

                    b.Navigation("BranchPharmacy");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("HospitalSys.Models.Receptionist", b =>
                {
                    b.HasOne("HospitalSys.Models.Users", "Users")
                        .WithMany("Receptionist")
                        .HasForeignKey("UsersUserID");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("HospitalSys.Models.Users", b =>
                {
                    b.HasOne("HospitalSys.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HospitalSys.Models.BillingAndPayment.Bill", b =>
                {
                    b.Navigation("BillItem");

                    b.Navigation("PaymentHospital");
                });

            modelBuilder.Entity("HospitalSys.Models.Cashier", b =>
                {
                    b.Navigation("Bill");

                    b.Navigation("PaymentHospital");
                });

            modelBuilder.Entity("HospitalSys.Models.Consultation_M.Consultation", b =>
                {
                    b.Navigation("MedicalRecord");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("HospitalSys.Models.Doctor", b =>
                {
                    b.Navigation("Admission");

                    b.Navigation("Appointment");

                    b.Navigation("Consultation");

                    b.Navigation("MedicalRecord");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("HospitalSys.Models.HospitalStruct.Bed", b =>
                {
                    b.Navigation("Admission");
                });

            modelBuilder.Entity("HospitalSys.Models.HospitalStruct.ClinicalDepartment", b =>
                {
                    b.Navigation("Doctor");

                    b.Navigation("Nurse");

                    b.Navigation("Triage");
                });

            modelBuilder.Entity("HospitalSys.Models.HospitalStruct.Room", b =>
                {
                    b.Navigation("Bed");
                });

            modelBuilder.Entity("HospitalSys.Models.HospitalStruct.TriageDepartment", b =>
                {
                    b.Navigation("Triage");
                });

            modelBuilder.Entity("HospitalSys.Models.HospitalStruct.Ward", b =>
                {
                    b.Navigation("Room");
                });

            modelBuilder.Entity("HospitalSys.Models.Nurse", b =>
                {
                    b.Navigation("Triage");
                });

            modelBuilder.Entity("HospitalSys.Models.PatientManagment.Patient", b =>
                {
                    b.Navigation("Admission");

                    b.Navigation("Appointment");

                    b.Navigation("Bill");

                    b.Navigation("MedicalRecord");

                    b.Navigation("PatientVist");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("HospitalSys.Models.PatientManagment.PatientVist", b =>
                {
                    b.Navigation("Bill");

                    b.Navigation("Consultation");

                    b.Navigation("Triage");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacist", b =>
                {
                    b.Navigation("AidStoreRequest");

                    b.Navigation("CentralStoreRequest");

                    b.Navigation("DispenseMedicine");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.AidStore.AidStorePharmacy", b =>
                {
                    b.Navigation("AidStoreInventory");

                    b.Navigation("AidStoreTransfer");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.AidStore.AidStoreRequest", b =>
                {
                    b.Navigation("AidStoreRequestDetail");

                    b.Navigation("AidStoreTransfer");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.AidStore.AidStoreTransfer", b =>
                {
                    b.Navigation("CentralStoreTransferDetail");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.Branch.BranchPharmacy", b =>
                {
                    b.Navigation("AidStoreRequest");

                    b.Navigation("AidStoreTransfer");

                    b.Navigation("BranchInventory");

                    b.Navigation("CentralStoreRequest");

                    b.Navigation("CentralStoreTransfer");

                    b.Navigation("DispenseMedicine");

                    b.Navigation("Pharmacist");

                    b.Navigation("PharmacyCashier");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.CentralStore.CentralStorePharmacy", b =>
                {
                    b.Navigation("CentralStoreInventory");

                    b.Navigation("CentralStoreTransfer");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.CentralStore.CentralStoreRequest", b =>
                {
                    b.Navigation("CentralStoreRequestDetail");

                    b.Navigation("CentralStoreTransfer");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.CentralStore.CentralStoreTransfer", b =>
                {
                    b.Navigation("CentralStoreTransferDetail");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.Common.DispenseMedicine", b =>
                {
                    b.Navigation("DispenseMedicineDetails");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.Common.Medicine", b =>
                {
                    b.Navigation("AidStoreInventory");

                    b.Navigation("AidStoreRequestDetail");

                    b.Navigation("BranchInventory");

                    b.Navigation("CentralStoreInventory");

                    b.Navigation("CentralStoreRequestDetail");

                    b.Navigation("CentralStoreTransfer");

                    b.Navigation("DispenseMedicineDetail");

                    b.Navigation("PrescriptionDetail");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacy.Common.Prescription", b =>
                {
                    b.Navigation("DispenseMedicine");

                    b.Navigation("PharmacyPayment");

                    b.Navigation("PrescriptionDetail");
                });

            modelBuilder.Entity("HospitalSys.Models.PharmacyCashier", b =>
                {
                    b.Navigation("PharmacyPayment");
                });

            modelBuilder.Entity("HospitalSys.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("HospitalSys.Models.Users", b =>
                {
                    b.Navigation("AidStorePharmacy");

                    b.Navigation("Cashier");

                    b.Navigation("CentralStorePharmacy");

                    b.Navigation("Doctor");

                    b.Navigation("LaboratoryTechnician");

                    b.Navigation("Nurse");

                    b.Navigation("Pharmacist");

                    b.Navigation("PharmacyCashier");

                    b.Navigation("Receptionist");
                });
#pragma warning restore 612, 618
        }
    }
}
