// <auto-generated />
using System;
using HospitalSys.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HospitalSys.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HospitalSys.Models.Cashier", b =>
                {
                    b.Property<int>("CashierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CashierID"));

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<int?>("UsersUserID")
                        .HasColumnType("integer");

                    b.HasKey("CashierID");

                    b.HasIndex("UsersUserID");

                    b.ToTable("Cashiers");
                });

            modelBuilder.Entity("HospitalSys.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DoctorID"));

                    b.Property<int>("ClinicalDepartmentID")
                        .HasMaxLength(200)
                        .HasColumnType("integer");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<int?>("UsersUserID")
                        .HasColumnType("integer");

                    b.HasKey("DoctorID");

                    b.HasIndex("ClinicalDepartmentID");

                    b.HasIndex("UsersUserID");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("HospitalSys.Models.HospitalStruct.ClinicalDepartment", b =>
                {
                    b.Property<int>("ClinicalDepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClinicalDepartmentID"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("ClinicalDepartmentID");

                    b.ToTable("ClinicalDepartments");
                });

            modelBuilder.Entity("HospitalSys.Models.HospitalStruct.TriageDepartment", b =>
                {
                    b.Property<int>("TriageDepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TriageDepartmentID"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("TriageDepartmentID");

                    b.ToTable("TriageDepartments");
                });

            modelBuilder.Entity("HospitalSys.Models.LaboratoryTechnician", b =>
                {
                    b.Property<int>("TechnicianID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TechnicianID"));

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<int?>("UsersUserID")
                        .HasColumnType("integer");

                    b.HasKey("TechnicianID");

                    b.HasIndex("UsersUserID");

                    b.ToTable("LaboratoryTechnicians");
                });

            modelBuilder.Entity("HospitalSys.Models.Nurse", b =>
                {
                    b.Property<int>("NurseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NurseID"));

                    b.Property<int>("ClinicalDepartmentID")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<int?>("UsersUserID")
                        .HasColumnType("integer");

                    b.HasKey("NurseID");

                    b.HasIndex("ClinicalDepartmentID");

                    b.HasIndex("UsersUserID");

                    b.ToTable("Nurses");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacist", b =>
                {
                    b.Property<int>("PharmacistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PharmacistID"));

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<int?>("UsersUserID")
                        .HasColumnType("integer");

                    b.HasKey("PharmacistID");

                    b.HasIndex("UsersUserID");

                    b.ToTable("Pharmacists");
                });

            modelBuilder.Entity("HospitalSys.Models.Receptionist", b =>
                {
                    b.Property<int>("ReceptionistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReceptionistID"));

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<int?>("UsersUserID")
                        .HasColumnType("integer");

                    b.HasKey("ReceptionistID");

                    b.HasIndex("UsersUserID");

                    b.ToTable("Receptionists");
                });

            modelBuilder.Entity("HospitalSys.Models.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleID"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("HospitalSys.Models.SuperAdmins", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("AdminRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ID");

                    b.ToTable("SuperAdmin");
                });

            modelBuilder.Entity("HospitalSys.Models.Users", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("RoleID")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("UserID");

                    b.HasIndex("RoleID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HospitalSys.Models.Cashier", b =>
                {
                    b.HasOne("HospitalSys.Models.Users", "Users")
                        .WithMany("Cashier")
                        .HasForeignKey("UsersUserID");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("HospitalSys.Models.Doctor", b =>
                {
                    b.HasOne("HospitalSys.Models.HospitalStruct.ClinicalDepartment", "ClinicalDepartment")
                        .WithMany("Doctor")
                        .HasForeignKey("ClinicalDepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalSys.Models.Users", "Users")
                        .WithMany("Doctor")
                        .HasForeignKey("UsersUserID");

                    b.Navigation("ClinicalDepartment");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("HospitalSys.Models.LaboratoryTechnician", b =>
                {
                    b.HasOne("HospitalSys.Models.Users", "Users")
                        .WithMany("LaboratoryTechnician")
                        .HasForeignKey("UsersUserID");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("HospitalSys.Models.Nurse", b =>
                {
                    b.HasOne("HospitalSys.Models.HospitalStruct.ClinicalDepartment", "ClinicalDepartment")
                        .WithMany("Nurse")
                        .HasForeignKey("ClinicalDepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalSys.Models.Users", "Users")
                        .WithMany("Nurse")
                        .HasForeignKey("UsersUserID");

                    b.Navigation("ClinicalDepartment");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("HospitalSys.Models.Pharmacist", b =>
                {
                    b.HasOne("HospitalSys.Models.Users", "Users")
                        .WithMany("Pharmacist")
                        .HasForeignKey("UsersUserID");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("HospitalSys.Models.Receptionist", b =>
                {
                    b.HasOne("HospitalSys.Models.Users", "Users")
                        .WithMany("Receptionist")
                        .HasForeignKey("UsersUserID");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("HospitalSys.Models.Users", b =>
                {
                    b.HasOne("HospitalSys.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HospitalSys.Models.HospitalStruct.ClinicalDepartment", b =>
                {
                    b.Navigation("Doctor");

                    b.Navigation("Nurse");
                });

            modelBuilder.Entity("HospitalSys.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("HospitalSys.Models.Users", b =>
                {
                    b.Navigation("Cashier");

                    b.Navigation("Doctor");

                    b.Navigation("LaboratoryTechnician");

                    b.Navigation("Nurse");

                    b.Navigation("Pharmacist");

                    b.Navigation("Receptionist");
                });
#pragma warning restore 612, 618
        }
    }
}
